name: Manual Build & Push Multi-Arch Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push - ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: [debian]
        tag: [latest]
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.IMAGE }}
        tags: ${{ matrix.tag }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.dockerfile }}
        file: ./${{ matrix.dockerfile }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: false
        cache-from: type=local,src=/tmp/.buildx-cache

    - name: Scan Docker Image
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: ${{ vars.IMAGE }}:${{ matrix.tag }}
        severity: HIGH,CRITICAL
        ignore-unfixed: true
